name: Build docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          token: ${{ secrets.DOCS_BOT_PAT }}
      - name: git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "theOGognf"
      - name: Merge main
        run: |
          git fetch
          git merge -X theirs origin/main -m "Merge main" --allow-unrelated-histories
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Build docs
        run: tox -e docs-single
      - name: Update docs
        run: |
          rm -rf docs
          mv singlehtml docs
          git add -f doctrees/
          git add -f singlehtml/
          git commit -m "Update docs"
          git push -f origin
