name: tox tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Run tests
        env:
          BEA_API_KEY: ${{ secrets.BEA_API_KEY }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          SEC_API_USER_AGENT: ${{ secrets.SEC_API_USER_AGENT }}
        run: tox -e test
      - name: Run static typechecks
        run: tox -e typecheck
      - name: Run lint
        run: tox -e lint
